
---
title: "Measles in Berlin Visualization"
author: "Michael Höhle"
date: "06 Mar 2016"
output: html_document
---

This is R code mimicking the analysis performed in [Wie-sich-die-Masern-in-Berlin-ausbreiten.html](http://www.morgenpost.de/berlin/article137810495/Wie-sich-die-Masern-in-Berlin-ausbreiten.html)
using the R package [surveillance](https://surveillance.r-forge.r-project.org).


```{r}
library("knitr")
opts_chunk$set(warning=FALSE,message=FALSE)
```
```{r}
library("surveillance")
library("ISOweek")
library("rgdal")

###Read survstat measles data for Berlin (queried from https://survstat.rki.de/)
survstat <- read.csv("survstat/Data.csv",fileEncoding="UCS-2LE",sep="\t")
###massage data
dates <- ISOweek2date(paste0(gsub("w","W",as.character(survstat[,1])),"-1"))
names <- gsub("City\\.of\\.Berlin\\.","",names(survstat)[-1])
names <- gsub("\\.","-",names)
names(survstat)[-1] <- names

### Get a shape with the bezirke
###Why doesn't the raw reading from github work?
###check: http://stackoverflow.com/questions/14441729/read-a-csv-from-github-into-r
###Alternative: use Rcurl
if (!file.exists("berliner-bezirke.kml")) {
  download.file("https://raw.githubusercontent.com/m-hoerz/berlin-shapes/master/berliner-bezirke.kml",
                destfile = "berliner-bezirke.kml", method = "curl")
}
bezirke <- readOGR("berliner-bezirke.kml","berliner_bezirke")

###Match row.names & order in survstat and shape file
order <- pmatch(names, as.character(as(bezirke,"data.frame")$Name))
bezirke <- bezirke[order,]
###Sanity check
all(as.character(as(bezirke,"data.frame")$Name) == names)
row.names(bezirke) <- names

##Look at result
plot(bezirke)
text(coordinates(bezirke),row.names(bezirke),cex=0.4)
```

```{r}
###Make sts object
measles <- new("sts",observed=survstat[,-1],epoch=as.numeric(dates),epochAsDate=TRUE,map=bezirke)

#For sake of better visualization we only take everything from 2011 and onwards
measles2011ao <- measles[epoch(measles) > as.Date("2011-01-01"),]

###Illustrate overall series
plot(aggregate(measles2011ao,by="unit"),legend.opts=NULL,
     xaxis.tickFreq=list("%W"=atChange,"%m"=atChange,"%Y"=atChange),
                xaxis.labelFreq=list("%Y"=atMedian),xaxis.labelFormat="%Y",
     ylab="No. reported",xlab="Time (weeks)")
```

```{r}
par(mar=c(3,3,0,0))
###Illustrate individual series
plot(measles2011ao,legend.opts=NULL,
     xaxis.tickFreq=list("%W"=atChange,"%m"=atChange,"%Y"=atChange),
                xaxis.labelFreq=list("%Y"=atMedian),xaxis.labelFormat="%Y",
     ylab="No. reported",xlab="Time (weeks)")

```

```{r eval=FALSE}
###Create animation --
library("animation")
saveHTML(animate(measles2011ao))
```

```{r eval=TRUE}
###Create animation --
library("animation")

which <- (epoch(measles) > as.Date("2014-10-01")) & (epoch(measles) < as.Date("2015-10-01"))
measles_sts <- new("sts",observed=survstat[which,-1],epoch=as.numeric(dates[which]),map=bezirke, epochAsDate=TRUE)
saveGIF(animate(measles_sts))
```
